### PR TITLE
parametrizing the ipfs gateway urls for fetch

### PR DESCRIPTION
**Pull request by sudeepdino008**
- ideal list of gateway urls might change. So removing the hardcoded values from codebase which would have otherwise needed a full rebuild and release if the list changes.

### CODE REVIEW

**Review by noslav — CHANGES_REQUESTED** [review]
How do you pass new ipfs gateways to ipfs-pinner instead of the add and rebuild? can you please document this?

**Comment by sudeepdino008** [comment]
@noslav please check now

**Comment by noslav** [comment]
> @noslav please check now

what should I check?

**Comment by sudeepdino008** [comment]
yes, missed the push; please check now

**Review by noslav — APPROVED** [review]
LGTM + tested with rudder stable stack 👍🏼

**Pull request merged**
